### ISSUE TITLE
Error in ./convertGenbank2table.py

### ISSUE THREAD

**Issue by meileel** [mattb112885/clusterDbAnalysis#69]
Hi Matt,
I have the following error keep popping up when I need to convert the genebank file

itep@itep-VirtualBox:~/LATEST_ITEP/master$ ./convertGenbank2table.py -g ReferenceGenome/ITEPref/psyringaeB301D.gbk -v 1
Traceback (most recent call last):
  File "./convertGenbank2table.py", line 285, in <module>
    if float(Bio.__version__) < RECOMMENDED_BIOPYTHON_VERSION:
ValueError: invalid literal for float(): 1.62b
itep@itep-VirtualBox:~/LATEST_ITEP/master$

Please let me know how to solve the error. 
Thanks
Meilee

**Comment by JosephRyanPeterson** [comment]
Hi Meilee,

Which version of itep did you download? The newest version in trunk doesn't have that line.

Sincerely,
Joseph

**Comment by meileel** [comment]
Hi Joseph,
It is the 64bit version1.1
Best,
Meilee

**Comment by JosephRyanPeterson** [comment]
Is this the virtual machine from this website: https://price.systemsbiology.org/research/itep/  ?

**Comment by meileel** [comment]
Yes, this is the one from the website.

**Comment by JosephRyanPeterson** [comment]
You may try downloading the source version from github here.  Otherwise you could try installing a different version of Biopython (e.g. one that isn't beta; the 1.62b indicates that there is a beta version installed).

**Comment by meileel** [comment]
Problems solved. Thanks!!
