### ISSUE TITLE
Error with rpsblast

### ISSUE THREAD

**Issue by mkroege1** [mattb112885/clusterDbAnalysis#75]
Everything is updated regarding blast+ and rpsblast on my machine, but rpsblast has different arguments now and so instead of -query it uses -i and -d for database instead of -db and -o for output instead of -o etc. This needs to be updated within the setup_step4.sh because currently it does not function due to the invalid arguments.

Example:
rpsblast -query faa/6666666.173663.txt.faa -db cd_db/Cdd.pn -out rpsblast_res/6666666.173663.txt.faa_rpsout -outfmt 6 -evalue 1.000000e-05
[rpsblast] ERROR: Invalid argument: -query

I can do it by hand and it works:
rpsblast -i faa/6666666.168144.txt.faa -d cd_db/Cdd.pn -o rpsblast_res/6666666.168144.txt.faa_rpsout -e 1e-05 -m 1 -a 16

Thanks.

**Comment by mattb112885** [comment]
Sorry, You don't have the latest version. Your help should look like this if you have a recent enough version (after 2.2.28). It may not be the latest in your package manager -- you can download it from here:

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ 

USAGE
  rpsblast [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-db database_name]
    [-dbsize num_letters] [-entrez_query entrez_query] [-query input_file]
    [-out output_file] [-evalue evalue] [-qcov_hsp_perc float_value]
    [-max_hsps int_value] [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-seg SEG_options] [-soft_masking soft_masking]
    [-culling_limit int_value] [-best_hit_overhang float_value]
    [-best_hit_score_edge float_value] [-window_size int_value]
    [-lcase_masking] [-query_loc range] [-parse_deflines] [-outfmt format]
    [-show_gis] [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-remote] [-comp_based_stats compo]
    [-use_sw_tback] [-version]

DESCRIPTION
   Reverse Position Specific BLAST 2.3.0+

Use '-help' to print detailed descriptions of command line arguments
