### ISSUE TITLE
Error in setup_step1.sh

### ISSUE THREAD

**Issue by mbeasier** [mattb112885/clusterDbAnalysis#83]
I encountered a problem when I tried to build the database with setup_step1.sh.The error message said that database or disk is full.But my disk isn't full, the problem must came from database and I don't know what was it.
Would anyone can help me with this problem?

**Comment by mattb112885** [comment]
Some previous people who had this issue said it was fixed with a newer version of sqlite. https://github.com/mattb112885/clusterDbAnalysis/issues/76 

It is also possible that if you have multiple partitions, the partition with your /tmp/ directory is filling up (sqlite needs to use this folder for staging).

**Comment by minimalismGeek** [comment]
> Some previous people who had this issue said it was fixed with a newer version of sqlite. #76
> 
> It is also possible that if you have multiple partitions, the partition with your /tmp/ directory is filling up (sqlite needs to use this folder for staging).

I have solved this problem by following the Known Issue in Wiki,.But I got another problem when I used the python file db_findClustersByOrganisms.py in /src, it reported the error that ImportError: cannot import name TextFace.I'll be appreciated if you can help me with this problem, thanks.

**Comment by mattb112885** [comment]
I haven't seen this issue before. It could be  a problem with dependencies of ETE itself:

 https://github.com/etetoolkit/ete/issues/195 

To be honest: You might want to take a look at Anvio (https://github.com/merenlab/anvio/tree/master/bin), ITEP isn't being updated any more, and that tool seems to do what ITEP does, but better. 

Matt

**Comment by minimalismGeek** [comment]
Thanks for your replies.I have solved my problems with your help.
